language: scala
sudo: required
dist: trusty

matrix:
  include:
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk9
  - stage: build
    env: CI_SCRIPT=ci/test-mill-release.sh
    jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.1.7/0.1.7-8-b913c6 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - "$CI_SCRIPT"

cache:
  directories:
  - $HOME/.coursier
